codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 10%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        # advanced settings
        branches:
          - develop
        if_ci_failed: error
        informational: false
        only_pulls: false
